### ISSUE TITLE
`CHANNEL_CAPACITY` is unused

### ISSUE THREAD

**Issue by drahnr** [paritytech/orchestra#28]
Since 0.0.5 I get the warning message `CHANNEL_CAPACITY` from generated code.

**Comment by vstakhov** [comment]
Indeed, this constant is no longer used as we use it in the builder implementation.

**Comment by vstakhov** [comment]
In the meantime, we also have `signal_channel_capacity`, is there any case if we want to have it per-subsystem specific? If yes, then we can unify all the code.

**Comment by drahnr** [comment]
The signal capacity is identical per subsystem, so we should never come to the point that we need different queues, unless there is a subsystem that blocks on tasks for a _very_ long time and does not process signals.

**Comment by vstakhov** [comment]
Yes, but if we can override message capacity per subsystem, why cannot we override a signal capacity then?

**Comment by drahnr** [comment]
Signals should be homogenous across all subsystems, and should be processed with priority iirc

**Comment by vstakhov** [comment]
Yes, but some subsystems might be slow, so signals sent to them might block other susbsystems, similarly to #18.

**Comment by drahnr** [comment]
This taps into https://github.com/paritytech/polkadot/issues/4019 whether that's ok or not or if we should split Signal Processing into its own stream entirely

**Comment by drahnr** [comment]
But I see that that'd be a large refactor mostly in polkadot, which might not be desirable at this point. Maybe it could be done by introducing prioritization into `prioritized-metered-channel`. But I degress.

The proposed approach is fine by me, but we should slow down the duck tape fixes needed short term for some more principal led arch refactors

**Comment by vstakhov** [comment]
In fact, I also think that having both `message_capacity` and `signal_capacity` on per-subsystem and per-overseer levels is a more consistent approach.
