### ISSUE TITLE
Disable signed commits

### ISSUE THREAD

**Issue by drahnr** [paritytech/orchestra#35]
Signed commits do not allow me to rebase, even if my branch sits _exactly_ on-top of `main`. So everything has to be squashed.

![image](https://user-images.githubusercontent.com/667047/219007993-6acac7e3-7e36-4b89-be7c-72ca006e3490.png)

**Comment by eskimor** [comment]
I don't think I am allowed to change this.

**Comment by drahnr** [comment]
> You can still do a rebase via CLI, as far as I know.

But then I'd have to push to `main`. Now we are at the point where signed commits introduce much more risk than it fixes.

> I don't think I am allowed to change this.

Yikes. Who can I talk to who has the power over that?

**Comment by sandreim** [comment]
I don't think it is a good practice to disable signed commits. Why can't we just use CLI to solve this ?

**Comment by drahnr** [comment]
When you say `cli`, are we talking about `git` or the `github` cli?

**Comment by drahnr** [comment]
GH Feedback: if the CI check passed, it can be pushed to master directly without force since that suffices for merge criteria. No force needed. U think that's what @vstakhov meant? Regardless, good enough for now.
