### ISSUE TITLE
Crates.io ownership

### ISSUE THREAD

**Issue by ordian** [paritytech/orchestra#4]
Hey @drahnr :wave: 

could you please 
```
cargo owner --add parity-crate-owner --add github:paritytech:core-devs
```
for `orchestra`, `orchestra-proc-macro` and `prioritized-metered-channel`? :pray: 

Thank you in advance :)

**Comment by drahnr** [comment]
I don't mind adding the `core-devs`, but I heard the birds singing that all other owners be removed as a general approach @paritytech , which is a bit opposing to what I'd need in using for my current employer. But maybe we can jump on a call, to make sure I am not being removed more or less accidentally :0

**Comment by bkchr** [comment]
> which is a bit opposing to what I'd need in using orchestra for my current employer

What does this mean?

If you contribute to this crate and require releases, I don't think that anyone will argue against this. To even make it easier we could include the same as for `ss58-registry`, releasing by CI every time there is a version bump.

**Comment by drahnr** [comment]
> > which is a bit opposing to what I'd need in using orchestra for my current employer
> 
> What does this mean?

Getting booted out of the release process would fall in that category. Other than that, no restrictions.

> If you contribute to this crate and require releases, I don't think that anyone will argue against this. To even make it easier we could include the same as for `ss58-registry`, releasing by CI every time there is a version bump.

Works for me.

**Comment by drahnr** [comment]
```
  the remote server responded with an error: could not find the github team paritytech/core-devs
```

**Comment by ordian** [comment]
Thank you!

I added `github:paritytech:core-devs` as well. This is good enough, will punt on adding `parity-crate-owner` for now.
