### ISSUE TITLE
Build failure since 0.3.4

### ISSUE THREAD

**Issue by drahnr** [paritytech/orchestra#70]
```
error[E0407]: method `recv_signal` is not a member of trait `orchestra::SubsystemContext`
  --> node/submesh/src/gen.rs:18:1
   |
18 | #[orchestra::orchestra(signal=SubMeshSignal, event=Event, error=SubMeshError, gen=AllMessages)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `orchestra::SubsystemContext`
   |
   = note: this error originates in the attribute macro `orchestra::orchestra` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0407`.
error: could not compile `submesh` (lib) due to previous error
```

**Comment by s0me0ne-unkn0wn** [comment]
Can you please elaborate on where this error comes from? Which repo? It's hard to tell without context, but I encountered a similar error when I was trying to build between the crates release when `orchestra-proc-macro` was already 0.3.4 and `orchestra` itself was 0.3.3. It could have been cached as well, so it may even be locally reproducible.

**Comment by drahnr** [comment]
Bottom line, this was a breaking change, not a patch release, since the public API exposed `recv_signal` from a trait that is commonly implemented in test helpers.
